name: Run tests & create release

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
    
env:
  NEW_VERSION: "4.0.1.${{github.run_number}}"

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['7.4', '8.0', '8.1', '8.2']

    steps:
      - uses: actions/checkout@v3

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
          extensions: mysql
          tools: composer:v2, phpunit

      - name: Run composer install
        run: composer install -n --prefer-dist

      - name: PHPUnit Tests
        run: phpunit --coverage-text
        
  release:
    needs: tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Find and Replace version
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: '4.0.1.\d+'
          replace: ${{env.NEW_VERSION}}
          regex: true,
          include: "src/CurlClient.php"
          
      - name: Auto commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated version

      - uses: avakar/tag-and-release@v1
        with:
          tag_name: ${{env.NEW_VERSION}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
